# -*- coding: utf-8 -*-
"""week4_titanic_ml.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ag326MFjQCuBhq_C7_L9qC_28EMbwJF-
"""

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

df = pd.read_csv("titanic_train.csv")

# ============================================================
# WEEK 4: MACHINE LEARNING MODEL DEVELOPMENT AND EVALUATION
# Dataset: Titanic
# ============================================================

# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score
)


# ------------------------------------------------------------
# 2. CREATE ASSETS FOLDER
# ------------------------------------------------------------

os.makedirs("assets", exist_ok=True)


# ------------------------------------------------------------
# 3. LOAD DATASET
# ------------------------------------------------------------

file_path = "titanic_train.csv"

df = pd.read_csv(file_path)

print("\n========== DATASET LOADED ==========")
print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())


# ------------------------------------------------------------
# 4. BASIC DATASET INFORMATION
# ------------------------------------------------------------

print("\n========== DATASET INFORMATION ==========")
print(df.info())

print("\n========== DESCRIPTIVE STATISTICS ==========")
print(df.describe())

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())


# ------------------------------------------------------------
# 5. MISSING VALUE VISUALIZATION
# ------------------------------------------------------------

missing = df.isnull().sum()
missing = missing[missing > 0]

plt.figure(figsize=(8, 5))
missing.plot(kind="bar")
plt.title("Missing Values by Feature")
plt.xlabel("Features")
plt.ylabel("Number of Missing Values")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("assets/missing_values.png", dpi=300)
plt.show()


# ------------------------------------------------------------
# 6. TARGET DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))
df["Survived"].value_counts().sort_index().plot(
    kind="bar"
)

plt.title("Titanic Survival Distribution")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("assets/target_distribution.png", dpi=300)
plt.show()


# ------------------------------------------------------------
# 7. SURVIVAL BY SEX
# ------------------------------------------------------------

survival_sex = pd.crosstab(
    df["Sex"],
    df["Survived"],
    normalize="index"
) * 100

survival_sex.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Survival Rate by Sex")
plt.xlabel("Sex")
plt.ylabel("Percentage")
plt.xticks(rotation=0)
plt.legend(["Did Not Survive", "Survived"])
plt.tight_layout()
plt.savefig("assets/survival_by_sex.png", dpi=300)
plt.show()


# ------------------------------------------------------------
# 8. SURVIVAL BY PASSENGER CLASS
# ------------------------------------------------------------

survival_class = pd.crosstab(
    df["Pclass"],
    df["Survived"],
    normalize="index"
) * 100

survival_class.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Survival Rate by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Percentage")
plt.xticks(rotation=0)
plt.legend(["Did Not Survive", "Survived"])
plt.tight_layout()
plt.savefig("assets/survival_by_class.png", dpi=300)
plt.show()


# ------------------------------------------------------------
# 9. DATA PREPROCESSING
# ------------------------------------------------------------

# Select useful features
features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

X = df[features].copy()
y = df["Survived"].copy()


# Fill missing numerical values
X["Age"] = X["Age"].fillna(X["Age"].median())

# Fill missing categorical values
X["Embarked"] = X["Embarked"].fillna(X["Embarked"].mode()[0])


# Convert categorical variables to numerical variables
X = pd.get_dummies(
    X,
    columns=["Sex", "Embarked"],
    drop_first=True
)


# Ensure all values are numeric
X = X.astype(float)


print("\n========== PROCESSED FEATURES ==========")
print(X.head())

print("\nProcessed dataset shape:", X.shape)


# ------------------------------------------------------------
# 10. TRAIN-TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\n========== TRAIN-TEST SPLIT ==========")
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])


# ------------------------------------------------------------
# 11. LOGISTIC REGRESSION MODEL
# ------------------------------------------------------------

logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    (
        "classifier",
        LogisticRegression(
            max_iter=1000,
            random_state=42
        )
    )
])

logistic_model.fit(X_train, y_train)

logistic_predictions = logistic_model.predict(X_test)
logistic_probabilities = logistic_model.predict_proba(X_test)[:, 1]


# ------------------------------------------------------------
# 12. RANDOM FOREST MODEL
# ------------------------------------------------------------

random_forest_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=6,
    min_samples_split=5,
    min_samples_leaf=2
)

random_forest_model.fit(X_train, y_train)

rf_predictions = random_forest_model.predict(X_test)
rf_probabilities = random_forest_model.predict_proba(X_test)[:, 1]


# ------------------------------------------------------------
# 13. MODEL EVALUATION FUNCTION
# ------------------------------------------------------------

def evaluate_model(model_name, y_true, predictions, probabilities):

    accuracy = accuracy_score(y_true, predictions)
    precision = precision_score(y_true, predictions)
    recall = recall_score(y_true, predictions)
    f1 = f1_score(y_true, predictions)
    auc = roc_auc_score(y_true, probabilities)

    print("\n========================================")
    print(model_name)
    print("========================================")

    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")
    print(f"ROC-AUC   : {auc:.4f}")

    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            predictions
        )
    )

    return accuracy, precision, recall, f1, auc


# ------------------------------------------------------------
# 14. EVALUATE LOGISTIC REGRESSION
# ------------------------------------------------------------

logistic_metrics = evaluate_model(
    "LOGISTIC REGRESSION",
    y_test,
    logistic_predictions,
    logistic_probabilities
)


# ------------------------------------------------------------
# 15. EVALUATE RANDOM FOREST
# ------------------------------------------------------------

rf_metrics = evaluate_model(
    "RANDOM FOREST",
    y_test,
    rf_predictions,
    rf_probabilities
)


# ------------------------------------------------------------
# 16. CONFUSION MATRIX - BEST MODEL
# ------------------------------------------------------------

# Select model based on F1 score
if rf_metrics[3] >= logistic_metrics[3]:
    best_predictions = rf_predictions
    best_probabilities = rf_probabilities
    best_model_name = "Random Forest"
else:
    best_predictions = logistic_predictions
    best_probabilities = logistic_probabilities
    best_model_name = "Logistic Regression"


cm = confusion_matrix(
    y_test,
    best_predictions
)

plt.figure(figsize=(7, 6))
plt.imshow(cm)

plt.title(f"Confusion Matrix - {best_model_name}")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.xticks(
    [0, 1],
    ["Did Not Survive", "Survived"]
)

plt.yticks(
    [0, 1],
    ["Did Not Survive", "Survived"]
)

for i in range(2):
    for j in range(2):
        plt.text(
            j,
            i,
            cm[i, j],
            ha="center",
            va="center"
        )

plt.tight_layout()
plt.savefig(
    "assets/confusion_matrix.png",
    dpi=300
)
plt.show()


# ------------------------------------------------------------
# 17. ROC CURVE
# ------------------------------------------------------------

logistic_fpr, logistic_tpr, _ = roc_curve(
    y_test,
    logistic_probabilities
)

rf_fpr, rf_tpr, _ = roc_curve(
    y_test,
    rf_probabilities
)

logistic_auc = roc_auc_score(
    y_test,
    logistic_probabilities
)

rf_auc = roc_auc_score(
    y_test,
    rf_probabilities
)

plt.figure(figsize=(8, 6))

plt.plot(
    logistic_fpr,
    logistic_tpr,
    label=f"Logistic Regression (AUC = {logistic_auc:.3f})"
)

plt.plot(
    rf_fpr,
    rf_tpr,
    label=f"Random Forest (AUC = {rf_auc:.3f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Random Classifier"
)

plt.title("ROC Curve Comparison")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.tight_layout()

plt.savefig(
    "assets/roc_curve.png",
    dpi=300
)

plt.show()


# ------------------------------------------------------------
# 18. CROSS-VALIDATION
# ------------------------------------------------------------

print("\n========== CROSS-VALIDATION ==========")

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

logistic_cv_scores = cross_val_score(
    logistic_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

rf_cv_scores = cross_val_score(
    random_forest_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("\nLogistic Regression CV Scores:")
print(logistic_cv_scores)

print(
    "Mean Logistic Regression CV Accuracy:",
    logistic_cv_scores.mean()
)

print(
    "Standard Deviation:",
    logistic_cv_scores.std()
)

print("\nRandom Forest CV Scores:")
print(rf_cv_scores)

print(
    "Mean Random Forest CV Accuracy:",
    rf_cv_scores.mean()
)

print(
    "Standard Deviation:",
    rf_cv_scores.std()
)


# ------------------------------------------------------------
# 19. MODEL COMPARISON TABLE
# ------------------------------------------------------------

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],

    "Accuracy": [
        logistic_metrics[0],
        rf_metrics[0]
    ],

    "Precision": [
        logistic_metrics[1],
        rf_metrics[1]
    ],

    "Recall": [
        logistic_metrics[2],
        rf_metrics[2]
    ],

    "F1 Score": [
        logistic_metrics[3],
        rf_metrics[3]
    ],

    "ROC-AUC": [
        logistic_metrics[4],
        rf_metrics[4]
    ],

    "CV Accuracy": [
        logistic_cv_scores.mean(),
        rf_cv_scores.mean()
    ]
})

print("\n========== MODEL COMPARISON ==========")
print(comparison.round(4))


# ------------------------------------------------------------
# 20. RANDOM FOREST FEATURE IMPORTANCE
# ------------------------------------------------------------

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": random_forest_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== FEATURE IMPORTANCE ==========")
print(feature_importance)


plt.figure(figsize=(9, 6))

plt.barh(
    feature_importance["Feature"],
    feature_importance["Importance"]
)

plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.gca().invert_yaxis()

plt.tight_layout()

plt.savefig(
    "assets/feature_importance.png",
    dpi=300
)

plt.show()


# ------------------------------------------------------------
# 21. FINAL RESULT
# ------------------------------------------------------------

print("\n========================================")
print("FINAL MODEL SELECTION")
print("========================================")

print("Best model based on F1 Score:", best_model_name)

print("\nFinal Model Comparison:")
print(comparison.round(4))

print("\nWeek 4 Machine Learning Analysis Completed Successfully.")

# ============================================================
# END OF WEEK 4 PROJECT
# ============================================================

missing = df.isnull().sum()
missing = missing[missing > 0]

plt.figure(figsize=(8, 5))
missing.plot(kind="bar")
plt.title("Missing Values by Feature")
plt.xlabel("Features")
plt.ylabel("Number of Missing Values")
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("missing_values.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7, 5))

df["Survived"].value_counts().sort_index().plot(kind="bar")

plt.title("Titanic Survival Distribution")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
plt.xticks(rotation=0)
plt.tight_layout()

plt.savefig("target_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

